"""add tenant relation to voters

Revision ID: 77baeef8bdf7
Revises: 3fb5ef3ab352
Create Date: 2025-10-22 19:31:13.176449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77baeef8bdf7'
down_revision: Union[str, Sequence[str], None] = '3fb5ef3ab352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
